const fs = require('fs');
const path = require('path');

console.log("=== 864Z Geo-Scripture Explorer Setup ===");

// 1. Determine which enriched JSON to use
let jsonSource = 'enriched-master-geodata.json';
if (fs.existsSync('enriched-master-geodata-first100.json')) {
    jsonSource = 'enriched-master-geodata-first100.json';
    console.log(`Detected verified first100 dataset. Using: ${jsonSource}`);
} else if (fs.existsSync('enriched-master-geodata-with-images.json')) {
    jsonSource = 'enriched-master-geodata-with-images.json';
    console.log(`Using dataset: ${jsonSource}`);
}

// 2. Compile JSON into a JS file to bypass CORS issues for local file:// testing
console.log("Compiling JSON to JS variable to bypass local CORS restrictions...");
try {
    const data = fs.readFileSync(jsonSource, 'utf8');
    const jsContent = `// Auto-generated by setup.js
const enrichedData = ${data};`;
    fs.writeFileSync('enriched-data.js', jsContent);
    console.log("✅ Successfully created enriched-data.js");
} catch (error) {
    console.error("❌ Failed to compile enriched data:", error.message);
}

// 3. Verify core files exist
const requiredFiles = ['index.html', 'style.css', 'main.js', 'geodata.js'];
let allGood = true;
console.log("
Verifying core application files...");
requiredFiles.forEach(file => {
    if (fs.existsSync(file)) {
        console.log(`✅ ${file} is present.`);
    } else {
        console.log(`❌ ${file} is missing!`);
        allGood = false;
    }
});

console.log("
=========================================");
if (allGood) {
    console.log("Setup Complete! You are ready to launch.");
    console.log(`-> Simply double-click 'index.html' located at:
   ${path.resolve('index.html')}`);
} else {
    console.log("Setup encountered issues. Please check the missing files.");
}
console.log("=========================================");
